name: ci

on: [push]

jobs:
  ci:
    env:
      # Needed for tests
      GITHUB_USER: rumpl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Tests
        run: make test
      - uses: codecov/codecov-action@v1
        with:
          file: ./profile.out
          fail_ci_if_error: true

      - name: Build
        run: make
